/**
 * Generated by orval v8.1.0 🍺
 * Do not edit manually.
 * Bootcamp Treinos API
 * Sample backend service
 * OpenAPI spec version: 1.0.0
 */
import { customFetch } from "../../fetch";
export type ListWorkoutPlansParams = {
  active?: ListWorkoutPlansActive;
};

export type ListWorkoutPlansActive =
  (typeof ListWorkoutPlansActive)[keyof typeof ListWorkoutPlansActive];

export const ListWorkoutPlansActive = {
  true: "true",
  false: "false",
} as const;

export type ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemWeekDay =
  (typeof ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemWeekDay)[keyof typeof ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemWeekDay];

export const ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  weekDay: ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  exercises: ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItemExercisesItem[];
};

export type ListWorkoutPlans200WorkoutPlansItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isActive: boolean;
  workoutDays: ListWorkoutPlans200WorkoutPlansItemWorkoutDaysItem[];
};

export type ListWorkoutPlans200 = {
  workoutPlans: ListWorkoutPlans200WorkoutPlansItem[];
};

export type ListWorkoutPlans401 = {
  error: string;
  code: string;
};

export type ListWorkoutPlans500 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlanBodyWorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlanBodyWorkoutDaysItemWeekDay];

export const CreateWorkoutPlanBodyWorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlanBodyWorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlanBodyWorkoutDaysItemWeekDay;
  isRest?: boolean;
  /** @minimum 0 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercises: CreateWorkoutPlanBodyWorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlanBody = {
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlanBodyWorkoutDaysItem[];
};

export type CreateWorkoutPlan201WorkoutDaysItemWeekDay =
  (typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay)[keyof typeof CreateWorkoutPlan201WorkoutDaysItemWeekDay];

export const CreateWorkoutPlan201WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type CreateWorkoutPlan201WorkoutDaysItemExercisesItem = {
  /** @minimum 0 */
  order: number;
  /** @minLength 1 */
  name: string;
  /** @minimum 1 */
  sets: number;
  /** @minimum 1 */
  reps: number;
  /** @minimum 1 */
  restTimeInSeconds: number;
};

export type CreateWorkoutPlan201WorkoutDaysItem = {
  /** @minLength 1 */
  name: string;
  weekDay: CreateWorkoutPlan201WorkoutDaysItemWeekDay;
  isRest: boolean;
  /** @minimum 0 */
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercises: CreateWorkoutPlan201WorkoutDaysItemExercisesItem[];
};

export type CreateWorkoutPlan201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @minLength 1 */
  name: string;
  workoutDays: CreateWorkoutPlan201WorkoutDaysItem[];
};

export type CreateWorkoutPlan400 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan401 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan404 = {
  error: string;
  code: string;
};

export type CreateWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan200WorkoutDaysItemWeekDay =
  (typeof GetWorkoutPlan200WorkoutDaysItemWeekDay)[keyof typeof GetWorkoutPlan200WorkoutDaysItemWeekDay];

export const GetWorkoutPlan200WorkoutDaysItemWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutPlan200WorkoutDaysItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  weekDay: GetWorkoutPlan200WorkoutDaysItemWeekDay;
  name: string;
  isRest: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  exercisesCount: number;
};

export type GetWorkoutPlan200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  workoutDays: GetWorkoutPlan200WorkoutDaysItem[];
};

export type GetWorkoutPlan401 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan404 = {
  error: string;
  code: string;
};

export type GetWorkoutPlan500 = {
  error: string;
  code: string;
};

export type GetWorkoutDay200WeekDay =
  (typeof GetWorkoutDay200WeekDay)[keyof typeof GetWorkoutDay200WeekDay];

export const GetWorkoutDay200WeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetWorkoutDay200ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  order: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  sets: number;
  reps: number;
  restTimeInSeconds: number;
};

export type GetWorkoutDay200SessionsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  startedAt: string | null;
  /**
   * @nullable
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  completedAt: string | null;
};

export type GetWorkoutDay200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  /** @nullable */
  coverImageUrl?: string | null;
  estimatedDurationInSeconds: number;
  weekDay: GetWorkoutDay200WeekDay;
  exercises: GetWorkoutDay200ExercisesItem[];
  sessions: GetWorkoutDay200SessionsItem[];
};

export type GetWorkoutDay401 = {
  error: string;
  code: string;
};

export type GetWorkoutDay404 = {
  error: string;
  code: string;
};

export type GetWorkoutDay500 = {
  error: string;
  code: string;
};

export type StartWorkoutSession201ExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  sourceWorkoutExerciseId: string | null;
  /**
   * @nullable
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  exerciseId: string | null;
  exerciseNameSnapshot: string;
  order: number;
  /** @nullable */
  plannedSets: number | null;
  /** @nullable */
  plannedReps: number | null;
  /** @nullable */
  plannedRestTimeInSeconds: number | null;
};

export type StartWorkoutSession201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  userWorkoutSessionId: string;
  exercises?: StartWorkoutSession201ExercisesItem[];
};

export type StartWorkoutSession401 = {
  error: string;
  code: string;
};

export type StartWorkoutSession404 = {
  error: string;
  code: string;
};

export type StartWorkoutSession409 = {
  error: string;
  code: string;
};

export type StartWorkoutSession422 = {
  error: string;
  code: string;
};

export type StartWorkoutSession500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSessionBody = {
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  completedAt: string;
};

export type UpdateWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  startedAt: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  completedAt: string;
};

export type UpdateWorkoutSession401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSession500 = {
  error: string;
  code: string;
};

export type GetHomeDataParams = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  timezoneOffset: number;
};

export type GetHomeData200TodayWorkoutDayWeekDay =
  (typeof GetHomeData200TodayWorkoutDayWeekDay)[keyof typeof GetHomeData200TodayWorkoutDayWeekDay];

export const GetHomeData200TodayWorkoutDayWeekDay = {
  MONDAY: "MONDAY",
  TUESDAY: "TUESDAY",
  WEDNESDAY: "WEDNESDAY",
  THURSDAY: "THURSDAY",
  FRIDAY: "FRIDAY",
  SATURDAY: "SATURDAY",
  SUNDAY: "SUNDAY",
} as const;

export type GetHomeData200TodayWorkoutDay = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutPlanId: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  name: string;
  isRest: boolean;
  weekDay: GetHomeData200TodayWorkoutDayWeekDay;
  estimatedDurationInSeconds: number;
  /** @nullable */
  coverImageUrl?: string | null;
  exercisesCount: number;
};

export type GetHomeData200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetHomeData200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  activeWorkoutPlanId: string;
  todayWorkoutDay?: GetHomeData200TodayWorkoutDay;
  workoutStreak: number;
  consistencyByDay: GetHomeData200ConsistencyByDay;
};

export type GetHomeData401 = {
  error: string;
  code: string;
};

export type GetHomeData404 = {
  error: string;
  code: string;
};

export type GetHomeData500 = {
  error: string;
  code: string;
};

export type GetStatsParams = {
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  from: string;
  /**
   * @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))$
   */
  to: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  timezoneOffset: number;
};

export type GetStats200ConsistencyByDay = {
  [key: string]: {
    workoutDayCompleted: boolean;
    workoutDayStarted: boolean;
  };
};

export type GetStats200 = {
  workoutStreak: number;
  consistencyByDay: GetStats200ConsistencyByDay;
  completedWorkoutsCount: number;
  conclusionRate: number;
  totalTimeInSeconds: number;
};

export type GetStats401 = {
  error: string;
  code: string;
};

export type GetStats500 = {
  error: string;
  code: string;
};

/**
 * @nullable
 */
export type GetUserTrainData200 = {
  userId: string;
  userName: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
} | null;

export type GetUserTrainData401 = {
  error: string;
  code: string;
};

export type GetUserTrainData404 = {
  error: string;
  code: string;
};

export type GetUserTrainData500 = {
  error: string;
  code: string;
};

export type UpsertUserTrainDataBody = {
  /** @minimum 1 */
  weightInGrams: number;
  /** @minimum 1 */
  heightInCentimeters: number;
  /** @minimum 1 */
  age: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  bodyFatPercentage: number;
};

export type UpsertUserTrainData200 = {
  userId: string;
  weightInGrams: number;
  heightInCentimeters: number;
  age: number;
  bodyFatPercentage: number;
};

export type UpsertUserTrainData401 = {
  error: string;
  code: string;
};

export type UpsertUserTrainData500 = {
  error: string;
  code: string;
};

export type GetActiveWorkoutSession200SessionExercisesItemSetsItemType =
  (typeof GetActiveWorkoutSession200SessionExercisesItemSetsItemType)[keyof typeof GetActiveWorkoutSession200SessionExercisesItemSetsItemType];

export const GetActiveWorkoutSession200SessionExercisesItemSetsItemType = {
  WARMUP: "WARMUP",
  WORKING: "WORKING",
} as const;

export type GetActiveWorkoutSession200SessionExercisesItemSetsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order: number;
  type: GetActiveWorkoutSession200SessionExercisesItemSetsItemType;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  weightInGrams: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  reps: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  rir: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  durationInSeconds: number | null;
  /** @nullable */
  notes: string | null;
  /** @nullable */
  completedAt: string | null;
};

export type GetActiveWorkoutSession200SessionExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  exerciseNameSnapshot: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  plannedSets: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  plannedReps: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  plannedRestTimeInSeconds: number | null;
  /** @nullable */
  notes: string | null;
  sets: GetActiveWorkoutSession200SessionExercisesItemSetsItem[];
};

export type GetActiveWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt: string;
  /** @nullable */
  completedAt: string | null;
  sessionExercises: GetActiveWorkoutSession200SessionExercisesItem[];
};

export type GetActiveWorkoutSession401 = {
  error: string;
  code: string;
};

export type GetActiveWorkoutSession404 = {
  error: string;
  code: string;
};

export type GetActiveWorkoutSession500 = {
  error: string;
  code: string;
};

export type GetWorkoutSession200SessionExercisesItemSetsItemType =
  (typeof GetWorkoutSession200SessionExercisesItemSetsItemType)[keyof typeof GetWorkoutSession200SessionExercisesItemSetsItemType];

export const GetWorkoutSession200SessionExercisesItemSetsItemType = {
  WARMUP: "WARMUP",
  WORKING: "WORKING",
} as const;

export type GetWorkoutSession200SessionExercisesItemSetsItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order: number;
  type: GetWorkoutSession200SessionExercisesItemSetsItemType;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  weightInGrams: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  reps: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  rir: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  durationInSeconds: number | null;
  /** @nullable */
  notes: string | null;
  /** @nullable */
  completedAt: string | null;
};

export type GetWorkoutSession200SessionExercisesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  exerciseNameSnapshot: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  plannedSets: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  plannedReps: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  plannedRestTimeInSeconds: number | null;
  /** @nullable */
  notes: string | null;
  sets: GetWorkoutSession200SessionExercisesItemSetsItem[];
};

export type GetWorkoutSession200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  workoutDayId: string;
  startedAt: string;
  /** @nullable */
  completedAt: string | null;
  sessionExercises: GetWorkoutSession200SessionExercisesItem[];
};

export type GetWorkoutSession401 = {
  error: string;
  code: string;
};

export type GetWorkoutSession404 = {
  error: string;
  code: string;
};

export type GetWorkoutSession500 = {
  error: string;
  code: string;
};

export type CreateWorkoutSetBodyType =
  (typeof CreateWorkoutSetBodyType)[keyof typeof CreateWorkoutSetBodyType];

export const CreateWorkoutSetBodyType = {
  WARMUP: "WARMUP",
  WORKING: "WORKING",
} as const;

export type CreateWorkoutSetBody = {
  type?: CreateWorkoutSetBodyType;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   * @nullable
   */
  weightInGrams?: number | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   * @nullable
   */
  reps?: number | null;
  /**
   * @minimum 0
   * @maximum 10
   * @nullable
   */
  rir?: number | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   * @nullable
   */
  durationInSeconds?: number | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  notes?: string | null;
  completed?: boolean;
};

export type CreateWorkoutSet201Type =
  (typeof CreateWorkoutSet201Type)[keyof typeof CreateWorkoutSet201Type];

export const CreateWorkoutSet201Type = {
  WARMUP: "WARMUP",
  WORKING: "WORKING",
} as const;

export type CreateWorkoutSet201 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  sessionExerciseId: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order: number;
  type: CreateWorkoutSet201Type;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  weightInGrams: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  reps: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  rir: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  durationInSeconds: number | null;
  /** @nullable */
  notes: string | null;
  /** @nullable */
  completedAt: string | null;
};

export type CreateWorkoutSet400 = {
  error: string;
  code: string;
};

export type CreateWorkoutSet401 = {
  error: string;
  code: string;
};

export type CreateWorkoutSet404 = {
  error: string;
  code: string;
};

export type CreateWorkoutSet409 = {
  error: string;
  code: string;
};

export type CreateWorkoutSet500 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSetBodyType =
  (typeof UpdateWorkoutSetBodyType)[keyof typeof UpdateWorkoutSetBodyType];

export const UpdateWorkoutSetBodyType = {
  WARMUP: "WARMUP",
  WORKING: "WORKING",
} as const;

export type UpdateWorkoutSetBody = {
  type?: UpdateWorkoutSetBodyType;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   * @nullable
   */
  weightInGrams?: number | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   * @nullable
   */
  reps?: number | null;
  /**
   * @minimum 0
   * @maximum 10
   * @nullable
   */
  rir?: number | null;
  /**
   * @minimum 0
   * @maximum 9007199254740991
   * @nullable
   */
  durationInSeconds?: number | null;
  /**
   * @maxLength 1000
   * @nullable
   */
  notes?: string | null;
  completed?: boolean;
};

export type UpdateWorkoutSet200Type =
  (typeof UpdateWorkoutSet200Type)[keyof typeof UpdateWorkoutSet200Type];

export const UpdateWorkoutSet200Type = {
  WARMUP: "WARMUP",
  WORKING: "WORKING",
} as const;

export type UpdateWorkoutSet200 = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  sessionExerciseId: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  order: number;
  type: UpdateWorkoutSet200Type;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  weightInGrams: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  reps: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  rir: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   * @nullable
   */
  durationInSeconds: number | null;
  /** @nullable */
  notes: string | null;
  /** @nullable */
  completedAt: string | null;
};

export type UpdateWorkoutSet400 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSet401 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSet404 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSet409 = {
  error: string;
  code: string;
};

export type UpdateWorkoutSet500 = {
  error: string;
  code: string;
};

export type DeleteWorkoutSet200 = {
  success: boolean;
};

export type DeleteWorkoutSet401 = {
  error: string;
  code: string;
};

export type DeleteWorkoutSet404 = {
  error: string;
  code: string;
};

export type DeleteWorkoutSet409 = {
  error: string;
  code: string;
};

export type DeleteWorkoutSet500 = {
  error: string;
  code: string;
};

/**
 * @summary List workout plans
 */
export type listWorkoutPlansResponse200 = {
  data: ListWorkoutPlans200;
  status: 200;
};

export type listWorkoutPlansResponse401 = {
  data: ListWorkoutPlans401;
  status: 401;
};

export type listWorkoutPlansResponse500 = {
  data: ListWorkoutPlans500;
  status: 500;
};

export type listWorkoutPlansResponseSuccess = listWorkoutPlansResponse200 & {
  headers: Headers;
};
export type listWorkoutPlansResponseError = (
  | listWorkoutPlansResponse401
  | listWorkoutPlansResponse500
) & {
  headers: Headers;
};

export type listWorkoutPlansResponse =
  | listWorkoutPlansResponseSuccess
  | listWorkoutPlansResponseError;

export const getListWorkoutPlansUrl = (params?: ListWorkoutPlansParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/workout-plans/?${stringifiedParams}`
    : `/workout-plans/`;
};

export const listWorkoutPlans = async (
  params?: ListWorkoutPlansParams,
  options?: RequestInit,
): Promise<listWorkoutPlansResponse> => {
  return customFetch<listWorkoutPlansResponse>(getListWorkoutPlansUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create a workout plan
 */
export type createWorkoutPlanResponse201 = {
  data: CreateWorkoutPlan201;
  status: 201;
};

export type createWorkoutPlanResponse400 = {
  data: CreateWorkoutPlan400;
  status: 400;
};

export type createWorkoutPlanResponse401 = {
  data: CreateWorkoutPlan401;
  status: 401;
};

export type createWorkoutPlanResponse404 = {
  data: CreateWorkoutPlan404;
  status: 404;
};

export type createWorkoutPlanResponse500 = {
  data: CreateWorkoutPlan500;
  status: 500;
};

export type createWorkoutPlanResponseSuccess = createWorkoutPlanResponse201 & {
  headers: Headers;
};
export type createWorkoutPlanResponseError = (
  | createWorkoutPlanResponse400
  | createWorkoutPlanResponse401
  | createWorkoutPlanResponse404
  | createWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type createWorkoutPlanResponse =
  | createWorkoutPlanResponseSuccess
  | createWorkoutPlanResponseError;

export const getCreateWorkoutPlanUrl = () => {
  return `/workout-plans/`;
};

export const createWorkoutPlan = async (
  createWorkoutPlanBody: CreateWorkoutPlanBody,
  options?: RequestInit,
): Promise<createWorkoutPlanResponse> => {
  return customFetch<createWorkoutPlanResponse>(getCreateWorkoutPlanUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createWorkoutPlanBody),
  });
};

/**
 * @summary Get a workout plan by ID
 */
export type getWorkoutPlanResponse200 = {
  data: GetWorkoutPlan200;
  status: 200;
};

export type getWorkoutPlanResponse401 = {
  data: GetWorkoutPlan401;
  status: 401;
};

export type getWorkoutPlanResponse404 = {
  data: GetWorkoutPlan404;
  status: 404;
};

export type getWorkoutPlanResponse500 = {
  data: GetWorkoutPlan500;
  status: 500;
};

export type getWorkoutPlanResponseSuccess = getWorkoutPlanResponse200 & {
  headers: Headers;
};
export type getWorkoutPlanResponseError = (
  | getWorkoutPlanResponse401
  | getWorkoutPlanResponse404
  | getWorkoutPlanResponse500
) & {
  headers: Headers;
};

export type getWorkoutPlanResponse =
  | getWorkoutPlanResponseSuccess
  | getWorkoutPlanResponseError;

export const getGetWorkoutPlanUrl = (id: string) => {
  return `/workout-plans/${id}`;
};

export const getWorkoutPlan = async (
  id: string,
  options?: RequestInit,
): Promise<getWorkoutPlanResponse> => {
  return customFetch<getWorkoutPlanResponse>(getGetWorkoutPlanUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get a workout day by ID
 */
export type getWorkoutDayResponse200 = {
  data: GetWorkoutDay200;
  status: 200;
};

export type getWorkoutDayResponse401 = {
  data: GetWorkoutDay401;
  status: 401;
};

export type getWorkoutDayResponse404 = {
  data: GetWorkoutDay404;
  status: 404;
};

export type getWorkoutDayResponse500 = {
  data: GetWorkoutDay500;
  status: 500;
};

export type getWorkoutDayResponseSuccess = getWorkoutDayResponse200 & {
  headers: Headers;
};
export type getWorkoutDayResponseError = (
  | getWorkoutDayResponse401
  | getWorkoutDayResponse404
  | getWorkoutDayResponse500
) & {
  headers: Headers;
};

export type getWorkoutDayResponse =
  | getWorkoutDayResponseSuccess
  | getWorkoutDayResponseError;

export const getGetWorkoutDayUrl = (id: string, dayId: string) => {
  return `/workout-plans/${id}/days/${dayId}`;
};

export const getWorkoutDay = async (
  id: string,
  dayId: string,
  options?: RequestInit,
): Promise<getWorkoutDayResponse> => {
  return customFetch<getWorkoutDayResponse>(getGetWorkoutDayUrl(id, dayId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Start a workout session
 */
export type startWorkoutSessionResponse201 = {
  data: StartWorkoutSession201;
  status: 201;
};

export type startWorkoutSessionResponse401 = {
  data: StartWorkoutSession401;
  status: 401;
};

export type startWorkoutSessionResponse404 = {
  data: StartWorkoutSession404;
  status: 404;
};

export type startWorkoutSessionResponse409 = {
  data: StartWorkoutSession409;
  status: 409;
};

export type startWorkoutSessionResponse422 = {
  data: StartWorkoutSession422;
  status: 422;
};

export type startWorkoutSessionResponse500 = {
  data: StartWorkoutSession500;
  status: 500;
};

export type startWorkoutSessionResponseSuccess =
  startWorkoutSessionResponse201 & {
    headers: Headers;
  };
export type startWorkoutSessionResponseError = (
  | startWorkoutSessionResponse401
  | startWorkoutSessionResponse404
  | startWorkoutSessionResponse409
  | startWorkoutSessionResponse422
  | startWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type startWorkoutSessionResponse =
  | startWorkoutSessionResponseSuccess
  | startWorkoutSessionResponseError;

export const getStartWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions`;
};

export const startWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  options?: RequestInit,
): Promise<startWorkoutSessionResponse> => {
  return customFetch<startWorkoutSessionResponse>(
    getStartWorkoutSessionUrl(workoutPlanId, workoutDayId),
    {
      ...options,
      method: "POST",
    },
  );
};

/**
 * @summary Update a workout session
 */
export type updateWorkoutSessionResponse200 = {
  data: UpdateWorkoutSession200;
  status: 200;
};

export type updateWorkoutSessionResponse401 = {
  data: UpdateWorkoutSession401;
  status: 401;
};

export type updateWorkoutSessionResponse404 = {
  data: UpdateWorkoutSession404;
  status: 404;
};

export type updateWorkoutSessionResponse500 = {
  data: UpdateWorkoutSession500;
  status: 500;
};

export type updateWorkoutSessionResponseSuccess =
  updateWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type updateWorkoutSessionResponseError = (
  | updateWorkoutSessionResponse401
  | updateWorkoutSessionResponse404
  | updateWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type updateWorkoutSessionResponse =
  | updateWorkoutSessionResponseSuccess
  | updateWorkoutSessionResponseError;

export const getUpdateWorkoutSessionUrl = (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
) => {
  return `/workout-plans/${workoutPlanId}/days/${workoutDayId}/sessions/${sessionId}`;
};

export const updateWorkoutSession = async (
  workoutPlanId: string,
  workoutDayId: string,
  sessionId: string,
  updateWorkoutSessionBody: UpdateWorkoutSessionBody,
  options?: RequestInit,
): Promise<updateWorkoutSessionResponse> => {
  return customFetch<updateWorkoutSessionResponse>(
    getUpdateWorkoutSessionUrl(workoutPlanId, workoutDayId, sessionId),
    {
      ...options,
      method: "PATCH",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(updateWorkoutSessionBody),
    },
  );
};

/**
 * @summary Get home page data
 */
export type getHomeDataResponse200 = {
  data: GetHomeData200;
  status: 200;
};

export type getHomeDataResponse401 = {
  data: GetHomeData401;
  status: 401;
};

export type getHomeDataResponse404 = {
  data: GetHomeData404;
  status: 404;
};

export type getHomeDataResponse500 = {
  data: GetHomeData500;
  status: 500;
};

export type getHomeDataResponseSuccess = getHomeDataResponse200 & {
  headers: Headers;
};
export type getHomeDataResponseError = (
  | getHomeDataResponse401
  | getHomeDataResponse404
  | getHomeDataResponse500
) & {
  headers: Headers;
};

export type getHomeDataResponse =
  | getHomeDataResponseSuccess
  | getHomeDataResponseError;

export const getGetHomeDataUrl = (date: string, params: GetHomeDataParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/home/${date}?${stringifiedParams}`
    : `/home/${date}`;
};

export const getHomeData = async (
  date: string,
  params: GetHomeDataParams,
  options?: RequestInit,
): Promise<getHomeDataResponse> => {
  return customFetch<getHomeDataResponse>(getGetHomeDataUrl(date, params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get workout statistics for a date range
 */
export type getStatsResponse200 = {
  data: GetStats200;
  status: 200;
};

export type getStatsResponse401 = {
  data: GetStats401;
  status: 401;
};

export type getStatsResponse500 = {
  data: GetStats500;
  status: 500;
};

export type getStatsResponseSuccess = getStatsResponse200 & {
  headers: Headers;
};
export type getStatsResponseError = (
  | getStatsResponse401
  | getStatsResponse500
) & {
  headers: Headers;
};

export type getStatsResponse = getStatsResponseSuccess | getStatsResponseError;

export const getGetStatsUrl = (params: GetStatsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/stats/?${stringifiedParams}`
    : `/stats/`;
};

export const getStats = async (
  params: GetStatsParams,
  options?: RequestInit,
): Promise<getStatsResponse> => {
  return customFetch<getStatsResponse>(getGetStatsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get user train data
 */
export type getUserTrainDataResponse200 = {
  data: GetUserTrainData200;
  status: 200;
};

export type getUserTrainDataResponse401 = {
  data: GetUserTrainData401;
  status: 401;
};

export type getUserTrainDataResponse404 = {
  data: GetUserTrainData404;
  status: 404;
};

export type getUserTrainDataResponse500 = {
  data: GetUserTrainData500;
  status: 500;
};

export type getUserTrainDataResponseSuccess = getUserTrainDataResponse200 & {
  headers: Headers;
};
export type getUserTrainDataResponseError = (
  | getUserTrainDataResponse401
  | getUserTrainDataResponse404
  | getUserTrainDataResponse500
) & {
  headers: Headers;
};

export type getUserTrainDataResponse =
  | getUserTrainDataResponseSuccess
  | getUserTrainDataResponseError;

export const getGetUserTrainDataUrl = () => {
  return `/me/`;
};

export const getUserTrainData = async (
  options?: RequestInit,
): Promise<getUserTrainDataResponse> => {
  return customFetch<getUserTrainDataResponse>(getGetUserTrainDataUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create or update user train data
 */
export type upsertUserTrainDataResponse200 = {
  data: UpsertUserTrainData200;
  status: 200;
};

export type upsertUserTrainDataResponse401 = {
  data: UpsertUserTrainData401;
  status: 401;
};

export type upsertUserTrainDataResponse500 = {
  data: UpsertUserTrainData500;
  status: 500;
};

export type upsertUserTrainDataResponseSuccess =
  upsertUserTrainDataResponse200 & {
    headers: Headers;
  };
export type upsertUserTrainDataResponseError = (
  | upsertUserTrainDataResponse401
  | upsertUserTrainDataResponse500
) & {
  headers: Headers;
};

export type upsertUserTrainDataResponse =
  | upsertUserTrainDataResponseSuccess
  | upsertUserTrainDataResponseError;

export const getUpsertUserTrainDataUrl = () => {
  return `/me/`;
};

export const upsertUserTrainData = async (
  upsertUserTrainDataBody: UpsertUserTrainDataBody,
  options?: RequestInit,
): Promise<upsertUserTrainDataResponse> => {
  return customFetch<upsertUserTrainDataResponse>(getUpsertUserTrainDataUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(upsertUserTrainDataBody),
  });
};

/**
 * @summary Chat with AI personal trainer
 */
export type postAiResponse200 = {
  data: void;
  status: 200;
};

export type postAiResponseSuccess = postAiResponse200 & {
  headers: Headers;
};
export type postAiResponse = postAiResponseSuccess;

export const getPostAiUrl = () => {
  return `/ai/`;
};

export const postAi = async (
  options?: RequestInit,
): Promise<postAiResponse> => {
  return customFetch<postAiResponse>(getPostAiUrl(), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Get current active workout session with all exercises and sets
 */
export type getActiveWorkoutSessionResponse200 = {
  data: GetActiveWorkoutSession200;
  status: 200;
};

export type getActiveWorkoutSessionResponse401 = {
  data: GetActiveWorkoutSession401;
  status: 401;
};

export type getActiveWorkoutSessionResponse404 = {
  data: GetActiveWorkoutSession404;
  status: 404;
};

export type getActiveWorkoutSessionResponse500 = {
  data: GetActiveWorkoutSession500;
  status: 500;
};

export type getActiveWorkoutSessionResponseSuccess =
  getActiveWorkoutSessionResponse200 & {
    headers: Headers;
  };
export type getActiveWorkoutSessionResponseError = (
  | getActiveWorkoutSessionResponse401
  | getActiveWorkoutSessionResponse404
  | getActiveWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type getActiveWorkoutSessionResponse =
  | getActiveWorkoutSessionResponseSuccess
  | getActiveWorkoutSessionResponseError;

export const getGetActiveWorkoutSessionUrl = () => {
  return `/workout-sessions/active`;
};

export const getActiveWorkoutSession = async (
  options?: RequestInit,
): Promise<getActiveWorkoutSessionResponse> => {
  return customFetch<getActiveWorkoutSessionResponse>(
    getGetActiveWorkoutSessionUrl(),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Get a workout session with all exercises and sets
 */
export type getWorkoutSessionResponse200 = {
  data: GetWorkoutSession200;
  status: 200;
};

export type getWorkoutSessionResponse401 = {
  data: GetWorkoutSession401;
  status: 401;
};

export type getWorkoutSessionResponse404 = {
  data: GetWorkoutSession404;
  status: 404;
};

export type getWorkoutSessionResponse500 = {
  data: GetWorkoutSession500;
  status: 500;
};

export type getWorkoutSessionResponseSuccess = getWorkoutSessionResponse200 & {
  headers: Headers;
};
export type getWorkoutSessionResponseError = (
  | getWorkoutSessionResponse401
  | getWorkoutSessionResponse404
  | getWorkoutSessionResponse500
) & {
  headers: Headers;
};

export type getWorkoutSessionResponse =
  | getWorkoutSessionResponseSuccess
  | getWorkoutSessionResponseError;

export const getGetWorkoutSessionUrl = (sessionId: string) => {
  return `/workout-sessions/${sessionId}`;
};

export const getWorkoutSession = async (
  sessionId: string,
  options?: RequestInit,
): Promise<getWorkoutSessionResponse> => {
  return customFetch<getWorkoutSessionResponse>(
    getGetWorkoutSessionUrl(sessionId),
    {
      ...options,
      method: "GET",
    },
  );
};

/**
 * @summary Create a new workout set for a session exercise
 */
export type createWorkoutSetResponse201 = {
  data: CreateWorkoutSet201;
  status: 201;
};

export type createWorkoutSetResponse400 = {
  data: CreateWorkoutSet400;
  status: 400;
};

export type createWorkoutSetResponse401 = {
  data: CreateWorkoutSet401;
  status: 401;
};

export type createWorkoutSetResponse404 = {
  data: CreateWorkoutSet404;
  status: 404;
};

export type createWorkoutSetResponse409 = {
  data: CreateWorkoutSet409;
  status: 409;
};

export type createWorkoutSetResponse500 = {
  data: CreateWorkoutSet500;
  status: 500;
};

export type createWorkoutSetResponseSuccess = createWorkoutSetResponse201 & {
  headers: Headers;
};
export type createWorkoutSetResponseError = (
  | createWorkoutSetResponse400
  | createWorkoutSetResponse401
  | createWorkoutSetResponse404
  | createWorkoutSetResponse409
  | createWorkoutSetResponse500
) & {
  headers: Headers;
};

export type createWorkoutSetResponse =
  | createWorkoutSetResponseSuccess
  | createWorkoutSetResponseError;

export const getCreateWorkoutSetUrl = (sessionExerciseId: string) => {
  return `/session-exercises/${sessionExerciseId}/sets`;
};

export const createWorkoutSet = async (
  sessionExerciseId: string,
  createWorkoutSetBody: CreateWorkoutSetBody,
  options?: RequestInit,
): Promise<createWorkoutSetResponse> => {
  return customFetch<createWorkoutSetResponse>(
    getCreateWorkoutSetUrl(sessionExerciseId),
    {
      ...options,
      method: "POST",
      headers: { "Content-Type": "application/json", ...options?.headers },
      body: JSON.stringify(createWorkoutSetBody),
    },
  );
};

/**
 * @summary Update an existing workout set
 */
export type updateWorkoutSetResponse200 = {
  data: UpdateWorkoutSet200;
  status: 200;
};

export type updateWorkoutSetResponse400 = {
  data: UpdateWorkoutSet400;
  status: 400;
};

export type updateWorkoutSetResponse401 = {
  data: UpdateWorkoutSet401;
  status: 401;
};

export type updateWorkoutSetResponse404 = {
  data: UpdateWorkoutSet404;
  status: 404;
};

export type updateWorkoutSetResponse409 = {
  data: UpdateWorkoutSet409;
  status: 409;
};

export type updateWorkoutSetResponse500 = {
  data: UpdateWorkoutSet500;
  status: 500;
};

export type updateWorkoutSetResponseSuccess = updateWorkoutSetResponse200 & {
  headers: Headers;
};
export type updateWorkoutSetResponseError = (
  | updateWorkoutSetResponse400
  | updateWorkoutSetResponse401
  | updateWorkoutSetResponse404
  | updateWorkoutSetResponse409
  | updateWorkoutSetResponse500
) & {
  headers: Headers;
};

export type updateWorkoutSetResponse =
  | updateWorkoutSetResponseSuccess
  | updateWorkoutSetResponseError;

export const getUpdateWorkoutSetUrl = (setId: string) => {
  return `/workout-sets/${setId}`;
};

export const updateWorkoutSet = async (
  setId: string,
  updateWorkoutSetBody: UpdateWorkoutSetBody,
  options?: RequestInit,
): Promise<updateWorkoutSetResponse> => {
  return customFetch<updateWorkoutSetResponse>(getUpdateWorkoutSetUrl(setId), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateWorkoutSetBody),
  });
};

/**
 * @summary Delete a workout set
 */
export type deleteWorkoutSetResponse200 = {
  data: DeleteWorkoutSet200;
  status: 200;
};

export type deleteWorkoutSetResponse401 = {
  data: DeleteWorkoutSet401;
  status: 401;
};

export type deleteWorkoutSetResponse404 = {
  data: DeleteWorkoutSet404;
  status: 404;
};

export type deleteWorkoutSetResponse409 = {
  data: DeleteWorkoutSet409;
  status: 409;
};

export type deleteWorkoutSetResponse500 = {
  data: DeleteWorkoutSet500;
  status: 500;
};

export type deleteWorkoutSetResponseSuccess = deleteWorkoutSetResponse200 & {
  headers: Headers;
};
export type deleteWorkoutSetResponseError = (
  | deleteWorkoutSetResponse401
  | deleteWorkoutSetResponse404
  | deleteWorkoutSetResponse409
  | deleteWorkoutSetResponse500
) & {
  headers: Headers;
};

export type deleteWorkoutSetResponse =
  | deleteWorkoutSetResponseSuccess
  | deleteWorkoutSetResponseError;

export const getDeleteWorkoutSetUrl = (setId: string) => {
  return `/workout-sets/${setId}`;
};

export const deleteWorkoutSet = async (
  setId: string,
  options?: RequestInit,
): Promise<deleteWorkoutSetResponse> => {
  return customFetch<deleteWorkoutSetResponse>(getDeleteWorkoutSetUrl(setId), {
    ...options,
    method: "DELETE",
  });
};
